typedef-ai/fenic

README.md
docs/index.md

- Update the link to the fenic Discord with one that is not expired.
- Update the doc site to link to the repository, and add a shield for the star count

docs: update discord link to a non-expired invite

---

.github/workflows/test.yaml
examples/document_extraction/document_extraction.py
examples/enrichment/enrichment.py
examples/feedback_clustering/feedback_clustering.py
examples/hello_world/hello_world.py
examples/json_processing/json_processing.py
examples/markdown_processing/markdown_processing.py
examples/meeting_transcript_processing/transcript_processing.py
examples/named_entity_recognition/ner.py
examples/news_analysis/news_analysis.py
examples/podcast_summarization/podcast_summarization.py
examples/semantic_joins/semantic_joins.py
tests/conftest.py
tests/examples/test_examples.py

Added optional `SessionConfig` parameter to all example scripts to enable testing with custom configurations.
- Modified all example scripts to accept an optional `SessionConfig` parameter in their `main()` functions
- Updated the implementation to use the provided config or create a default one if none is provided
- Fixed file path handling in the JSON processing example to use `Path` for more reliable file location
- Added a `gemini_session_config` fixture in `conftest.py` for testing examples
- Updated the example test to pass the test configuration to each example's main function
Run the example tests with:
```bash
pytest tests/examples/test_examples.py
```
You can also manually test any example by importing and calling its main function with a custom config:
```python
import fenic as …
```

test: update examples test to pass a session config, so we can use gemini model rate limits in CI

---

src/fenic/_backends/cloud/session_state.py

The default grpc message size is ~5MB, the proposal is to increase that default size to 10MB.
The size can be set using environment variables.

fix: increase the grpc default message size

---

src/fenic/__init__.py
src/fenic/_backends/cloud/engine_config.py
src/fenic/api/__init__.py
tests/conftest.py

Added support for Google GLA and Vertex AI models with proper API key handling.
- Added `CloudConfig` to the public API exports
- Enhanced model provider configuration in `EngineConfig` to support Google models:
- Added special handling for Google GLA models to check for either `GOOGLE_API_KEY` or `GEMINI_API_KEY`
- Added support for Google Vertex models which require `GOOGLE_CLOUD_PROJECT` and `GOOGLE_CLOUD_LOCATION` environment variables
- Updated the model provider detection logic to handle Google model configurations
- Refactored test configurations to reduce code duplication by creating a reusable OpenAI nano model configuration

fix: support google models in cloud

---

src/fenic/logging.py

TD-1570
Added `google_genai` to the list of noisy logger names to suppress non-error logs from. Also moved the list of noisy loggers to a constant so it's easier to see at a glance what's being ignored.

fix: suppress noisy gemini logs

---

.github/workflows/test.yaml
CONTRIBUTING.md
rust/Cargo.toml

This PR resolves linker errors that occur when running `cargo test` on the `polars-plugin` crate by disabling PyO3's `extension-module` feature during test builds.
The `polars-plugin` crate uses PyO3 to build a Python extension module. By default, it enables the `extension-module` feature, which is necessary for tools like `maturin` to build shared libraries (`*.so`/`*.pyd`) that are importable from Python.
However, enabling `extension-module` tells PyO3:
* To assume it is running inside a Python process
* To rely on Python symbols (e.g. `_PyExc_SystemError`) being available at runtime
This works fine for extension builds, but causes issues when running `cargo test`, because:
* The test binary is not loaded by Python
* No Python interpreter is running
* Python symbols are undefined at …

chore: enable rust unit tests in ci using cargo test with feature flag

---

src/fenic/_backends/cloud/catalog.py
src/fenic/_backends/cloud/manager.py
src/fenic/_backends/cloud/session_state.py
tests/_backends/cloud/catalog/test_cloud_catalog.py

Use a simple catalog way to determine if a table is available.
- Modified `CloudCatalog` initialization to accept direct parameters instead of depending on `CloudSessionState`
- Added a new `_get_table` method to improve table existence checking
- Updated `_does_table_exist` to use the new method instead of fetching all tables
- Updated tests to accommodate the new structure

fix: make catalog use sc method to implement does_table_exist

---

src/fenic/_backends/cloud/catalog.py
src/fenic/_backends/cloud/session_state.py
tests/_backends/cloud/test_cloud_execution.py

Fix replacement that wasn't meant to apply to the cloud files.

fix: rogue replacement of `name` with `model_name`

---

src/fenic/__init__.py
src/fenic/_backends/local/transpiler/expr_converter.py
src/fenic/api/__init__.py
src/fenic/api/functions/__init__.py
src/fenic/api/functions/builtin.py
src/fenic/core/_logical_plan/expressions/__init__.py
src/fenic/core/_logical_plan/expressions/basic.py
src/fenic/core/_logical_plan/signatures/basic.py
tests/_backends/local/functions/test_greatest_least.py
tests/api/test_session.py

This PR adds SQL-compatible `greatest()` and `least()` functions to find the maximum and minimum values across multiple columns within each row. These functions mirror the behavior of SQL's `GREATEST` and `LEAST` operations.
- **`greatest(*cols)`** - Returns the maximum value among the provided columns for each row
- **`least(*cols)`** - Returns the minimum value among the provided columns for each row
```python
df.select(greatest(col("score1"), col("score2"), col("score3")).alias("best_score"))
df.select(least(col("price1"), col("price2"), col("price3")).alias("lowest_price"))
```
- Functions require at least 2 arguments
- All arguments must be of the same primitive type (IntegerType, FloatType, StringType, BooleanType, etc.)
- Complex types (lists, structs) are not supported and will …

feat: add support for greatest/least column functions

---

justfile
src/fenic/_inference/common_openai/openai_chat_completions_core.py
src/fenic/_inference/language_model.py
src/fenic/_inference/openai/openai_batch_chat_completions_client.py
src/fenic/_inference/types.py
src/fenic/core/_inference/model_catalog.py
tests/conftest.py

Added support for GPT-5 models and fixed temperature handling for reasoning models.
- Added GPT-5 model family to the model catalog:
- `gpt-5` with snapshots (`gpt-5-2025-08-07`)
- `gpt-5-mini` with snapshots (`gpt-5-mini-2025-08-07`)
- `gpt-5-nano` with snapshots (`gpt-5-nano-2025-08-07`)
- Fixed temperature handling for reasoning models:
- Removed temperature parameter for OpenAI reasoning models
- Moved temperature check to the batch client instead of the core module
- Updated default test model from `gpt-4.1-nano` to `gpt-5-nano`
1. run semantic unit tests with each model
- Support for gpt-5-chat-latest, since it doesn't support Structured Outputs
- Adding verbosity field
- Updating reasoning level fields

feat: Add gpt-5 support

---

src/fenic/_backends/local/model_registry.py
src/fenic/_backends/local/session_state.py
tests/_backends/local/functions/test_embed.py

This part of the `session_state` interaction with `model_registry` was not updated when we added profile support to embedding models.

fix: model_registry now uses the new ResolvedModelAlias for embedding model lookup properly

---

examples/mcp/docs-server/README.md
examples/mcp/docs-server/pyproject.toml
examples/mcp/docs-server/search.py
examples/mcp/docs-server/server.py
examples/mcp/docs-server/tests/test_search.py
examples/mcp/docs-server/utils/schemas.py
examples/mcp/docs-server/utils/validation.py
examples/mcp/docs-server/uv.lock

Improved search functionality in the docs-server with better regex handling, structured logging, and enhanced error handling.
This uses the changes proposed by Brandon for our own MCP server. We'll use just the regex.
Also, I incorrectly assumed we didn't need the models for the server, that is not correct as store_learnings requires the models. I've added them back to the configuration and README.md.
I've tested also retrieving the information from the learnings (using the full string as well as the terms), this wasn't working properly as store_learnings was failing due to the lack of model configuration.

fix: only use regex search for the mcp server example

---

src/fenic/api/dataframe/dataframe.py

We don't yet support aggregate expression syntactic sugar directly on the GroupedData object and we require aggregate expressions inside the agg() function. This confused the MCP docs server.Aggregate expression syntactic sugar is not yet supported directly on the GroupedData object. Instead, aggregate expressions must be passed inside the agg() function. The example has been updated to use agg() instead of calling count() directly, since this caused confusion in the MCP docs server.

docs: fix group by docstring to use count() within agg()

---

src/fenic/_backends/cloud/catalog.py
src/fenic/_backends/cloud/cloud_catalog_utils.py
src/fenic/core/_utils/schema.py
tests/_backends/cloud/catalog/test_cloud_catalog.py

Replaced Polars-based schema serialization with Protocol Buffers for cloud catalog schema handling.
- Added a new `cloud_catalog_utils.py` file with PyArrow conversion utilities
- Serialize `fenic` DataType objects as base64 encoded binary strings
- Deserialize `fenic` DataType objects upon reading from cloud catalog table. 
- Updated schema handling in `CloudCatalog` to use the new serialization approach
- Added additional string backed types (Transcript, Embedding, Markdown, HTML, etc.) to conversion functions for polars and pyarrow. 
- Enhanced tests to verify proper serialization/deserialization of complex data types
1. Run the updated tests in `test_cloud_catalog.py`
2. Verify schema conversion works for all data types including complex ones
3. Test creating tables with various data …

feat: support logical types in cloud catalog 

---

src/fenic/_backends/local/utils/io_utils.py
src/fenic/api/io/reader.py
src/fenic/api/io/writer.py
tests/_backends/local/io/test_reader.py
tests/conftest.py

Added support for HuggingFace datasets in Fenic's I/O operations (reads only).
- Added support for the `hf://` scheme to read and write data from HuggingFace datasets
- Implemented HuggingFace token authentication via environment variables (`HF_TOKEN`) or AWS Secrets Manager
- Updated DuckDB query building to handle HuggingFace credentials
- Added support for mixed source queries (e.g., reading from both S3 and HuggingFace)
- Updated documentation to reflect the new supported storage scheme
- Added comprehensive tests for public and private HuggingFace datasets
1. Unit tests 
- Token reading and DuckDB query setup
- Failing to authenticate Token
- Reading CSV/Parquet, file lists, globs, hash revision
- Mixing HuggingFace source with s3/local
2. Not covered by Unit Tests: Test reading from …

feat: Add connector for reading huggingface scheme

---

src/fenic/_backends/local/async_utils.py
src/fenic/_backends/local/manager.py
src/fenic/_backends/local/transpiler/expr_converter.py

Here's a cleaned up PR description:
**Fix async task cleanup on interpreter shutdown and optimize generator handling**
This PR addresses two issues:
1. **Prevents "Task was destroyed but it is pending!" errors on program exit**
- The background asyncio thread runs long-running actors that continue executing when the program shuts down
- Without proper cleanup, these actors can't be cancelled, resulting in "Task was destroyed but it is pending!" errors
- This PR registers an `atexit` handler to properly cancel tasks, shutdown the event loop, and join the background thread
- The background thread still needs `daemon=True` because with `daemon=False`, the interpreter won't shut down until the thread is joined. This would require signaling shutdown through an event when the user script …

fix: shutdown event loop and cancel tasks on program exit

---

src/fenic/_backends/cloud/metrics.py
src/fenic/_backends/local/catalog.py
src/fenic/_backends/local/execution.py
src/fenic/_backends/local/physical_plan/base.py
src/fenic/_backends/local/session_state.py
src/fenic/_backends/local/system_table_client.py
src/fenic/_backends/utils/catalog_utils.py
src/fenic/api/catalog.py
src/fenic/api/session/session.py
src/fenic/core/metrics.py
tests/_backends/local/catalog/test_catalog.py
tests/_backends/local/catalog/test_metrics_table.py

Added a metrics tracking system that automatically records query execution statistics in a read-only `metrics` table.
- Created a new read-only `metrics` table that tracks query execution statistics
- Added concept of read-only database in the catalog: `fenic_system`
- Added ability to System_Table_client to insert metrics and aggregate from last session
- Added ability for session to manage metrics table through catalog api
- Enhanced `QueryMetrics` with session tracking and timestamp information
- Added session usage summary that displays at the end of a session
Session Usage Summary:
App Name: test_app
Session ID: 268f2b29-096a-4a90-bbd2-abb02e9a382b
Total queries executed: 4
Total execution time: 15.22ms
Total rows processed: 10
Total language model cost: $0.000000
Total embedding …

feat: local metrics table

---

src/fenic/_inference/common_openai/openai_chat_completions_core.py
src/fenic/_inference/common_openai/openai_embeddings_core.py

Added a TransientException if we get a 404 and no processing from OpenAI.
Fenic's batch processing should be able to handle the exception and perform the retry.
- The error handling for both openai chat and embeddings now handle the NotFoundError. if we have the headers and the headers indicate no work was done on OpenAI, we'll retry the operation.

fix: add retry to OpenAI for 404 errors when no processing was done

---

src/fenic/_inference/google/google_provider.py

Fixed a logging statement in the Google provider to use the correct attribute name.
1. Configure a Google provider with a valid API key
2. Enable debug logging
3. Run a validation of the API key
4. Verify that the debug log shows the correct provider name

fix: regression when using google provider and logger level DEBUG

---

src/fenic/_backends/cloud/execution.py
src/fenic/core/_inference/model_provider.py

Return actual query metrics for `save_as_table` and `save_to_file` operations instead of empty metrics, and fix cloud unit tests.
Modified the `save_as_table` and `save_to_file` methods in the cloud execution backend to return actual query execution metrics instead of empty placeholder metrics. This also fixes cloud unit tests, which broke with QueryMetric changes in 0.4.0.  Both methods now call `self._get_query_execution_metrics()` with the execution ID returned from the future result.
1. Run cloud unit tests, which test the save_as_file path

fix: cloud execution save_ methods should get metrics from backend

---

src/fenic/api/io/reader.py
src/fenic/core/error.py
tests/_backends/local/io/test_reader.py
tests/_logical_plan/serde/test_plan_serde.py

This reverts commit 083d61a56fc14979a77831841086c0f2f99781c9.
Long term, it will be better to have a unified API for all doc types as we add support for more doc types.

feat: revert "feat: split reader.docs() into json() and markdown() (#179)"

---

pyproject.toml
src/fenic/_backends/local/utils/doc_loader.py
src/fenic/api/io/reader.py
src/fenic/core/_logical_plan/plans/source.py
tests/_backends/local/io/test_doc_loader.py
tests/_backends/local/io/test_reader.py
tests/conftest.py
uv.lock

- Add a new reader function that extracts metadata from pdf globs and returns it in a dataframe
- similar to reader.json() and reader.markdown()
- Uses PyMuPDF to grab metadata from the files
- Add unit test functionality for generating pdfs of varying complexity
- Added testing

feat: reader.pdf_metadata for reading pdf metadata into a df

---

src/fenic/_backends/local/utils/io_utils.py
tests/_backends/local/io/test_reader.py
tests/_backends/local/test_session.py

Allow users to pull public datasets from Hugging Face and publicaly accessible files from S3 without setting up an HF_TOKEN/AWS_ACCESS_KEY. 
- Enhanced error handling in `query_files` and `write_file` functions to provide more specific error messages
- Modified credential handling functions to return a boolean indicating if credentials were found
- Added graceful fallback for HuggingFace paths without credentials (will attempt to read public datasets)
- Added warning logs when credentials are missing but operation might still succeed
- Added error handling for HTTP status codes (404, 401, 403) with contextual messages
- Updated tests to match the new error handling behavior
- Test reading from S3 with valid credentials, invalid credentials, and no credentials
- Test reading from …

fix: when querying files in public S3 buckets/HuggingFace Datasets, the user should not have to provide credentials

---

src/fenic/_inference/google/google_profile_manager.py
src/fenic/api/session/config.py
src/fenic/core/_inference/model_catalog.py
tests/conftest.py

Gemini-2.5-pro does not allow disabled reasoning.  We had special checks for the Profile path, but we weren't handling the default model path with no profiles properly.
With this change, user can configure gemini-2.5-pro in a single line without profiles and we default the thinking budget to 'low'.  Also introduced concept of ‘supports-disabled-reasoning’ to our model-params to remove special case code
Run unit tests with gemini-2.5-pro and removing all profiles to ensure default behavior works

fix: gemini-2.5-pro default model without profiles

---

tests/_backends/local/io/test_reader.py
tests/conftest.py

- PDF randomized content generation had a bug where sometimes it wouldn't generate the content it was asked to, causing test_read_large_pdfs_with_fields to be flaky
- This PR includes the bugfix, and some improved failure logging in test_read_large_pdfs_with_fields
Before the fix, failure rate was roughly 5%.  
Ran 1000 tests and made sure they were all green

fix: off-by-one bug in random pdf content generation for testing

---

src/fenic/api/mcp/_tool_generation_utils.py
src/fenic/api/mcp/server.py
src/fenic/core/mcp/_server.py
src/fenic/core/mcp/types.py
tests/api/mcp/test_tool_generation.py
tools/automated_mcp_demo_setup.py

- Make tool operation functions synchronous
- Have DatasetSpec lazily fetch the dataframe using `session.table` instead of keeping it in memory over the lifespan of the server. 
- Additionally, removed profile caching, and refactored the profile calculation mechanism to parallelize the calculations within polars.

refactor: have DatasetSpec lazily fetch the dataframe using `session.table` instead of keeping it in memory

---

src/fenic/_backends/local/semantic_operators/parse_pdf.py
src/fenic/_inference/common_openai/openai_utils.py
src/fenic/_inference/google/gemini_token_counter.py
src/fenic/_inference/google/google_utils.py
src/fenic/_inference/model_client.py
src/fenic/_inference/request_utils.py
src/fenic/_inference/types.py
src/fenic/api/functions/semantic.py
src/fenic/core/_logical_plan/expressions/semantic.py
tests/_backends/local/functions/test_semantic_parse_pdf.py
tests/_backends/local/semantic_operators/test_parse_pdf.py
tests/_inference/google/test_gemini_token_counter.py

Gemini models especially are limited by the output token limit, only 8K tokens (for flash-2.0). Added PDF parsing by implementing chunking-by-page for large documents, based on the models output token limit.
Also refactored file support in LMRequestMessage (added LMRequestFile), and ability for gemini to send chunked pdfs in requests
- Added support for processing PDFs in chunks based on page count and output token limits
- Chunking happens once, when requests are built
- These chunks are saved as bytes in the LMRequestMessage, in new LMRequestFile class
-`ParsePDF` operator will separate long PDFs into chunks with separate requests per chunk, then in postprocess, will concat the responses for each chunk into a single coherent output, honoring the page delimiter option
- Added internal …

feat: Add page chunking to semantic parse_pdf, refactor token estimation

---

docs/topics/fenic-mcp.md
src/fenic/api/mcp/server.py

Don't pass port/host to `http_app`​ as those arguments are not supported (since we are creating an ASGI app and not running the server with something like uvicorn).

fix: do not pass port to http_app, it is not accepted there

---

src/fenic/_inference/openrouter/openrouter_batch_chat_completions_client.py

Fixed openrouter client issues -- updated the OpenRouter batch chat completions client to use the common message conversion utility.
- Imported the `convert_messages` function from `fenic._inference.common_openai.openai_utils`
- Replaced the direct call to `request.messages.to_message_list()` with `convert_messages(request.messages)` in the `make_single_request` method

fix: openrouter batch completions client was broken after changes to LMRequestMessages
